### ISSUE TITLE
Feature request: Ranking 

### ISSUE THREAD

**Issue by Nabeelshar** [jusoftdev/searchify#3]
Ranking or trending keywords list like twitter or Baidu.

Also if you need hosting i can provide for this.(free)

**Comment by Nabeelshar** [comment]
Helpful resource s
https://rapidapi.com/joaomvferreira-f_HtLYVj40/api/what-is-hot-right-now/

**Comment by juhom205** [comment]
Thank you for your Suggestion! I love this idea, I will definitely look into it and implement it, when I have the time!
